### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by gordon-matt** [afaq-khan/NuspecGenerator#2]
I installed the vsix and clicked "Generate or update .nuspec", but nothing happened. No error message and no .nuspec file.

**Comment by afaq-khan** [comment]
Can you tell me what project type you tried this with? You can find the ProjectTypeGuids in the project file, e.g.  `<ProjectTypeGuids>{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>`.

Any errors should be logged to the output window of Nuspec Generator.

**Comment by afaq-khan** [comment]
Closing as no feedback has been received
